package com.xl.kffta.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.xl.kffta.model.sql.TaskInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "TASK_INFO".
 */
public class TaskInfoDao extends AbstractDao<TaskInfo, Long> {

    public static final String TABLENAME = "TASK_INFO";

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"OBJECT_ID\" INTEGER NOT NULL ," + // 1: objectId
                "\"EXECUTE_TIME\" INTEGER NOT NULL ," + // 2: executeTime
                "\"CODE_NAME\" TEXT NOT NULL ," + // 3: codeName
                "\"EXCUTION_STATUS\" INTEGER NOT NULL ," + // 4: excutionStatus
                "\"COMPANY_ID\" INTEGER NOT NULL ," + // 5: companyId
                "\"PAGE_CODE\" INTEGER NOT NULL );"); // 6: pageCode
    }


    public TaskInfoDao(DaoConfig config) {
        super(config);
    }
    
    public TaskInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getObjectId());
        stmt.bindLong(3, entity.getExecuteTime());
        stmt.bindString(4, entity.getCodeName());
        stmt.bindLong(5, entity.getExcutionStatus());
        stmt.bindLong(6, entity.getCompanyId());
        stmt.bindLong(7, entity.getPageCode());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getObjectId());
        stmt.bindLong(3, entity.getExecuteTime());
        stmt.bindString(4, entity.getCodeName());
        stmt.bindLong(5, entity.getExcutionStatus());
        stmt.bindLong(6, entity.getCompanyId());
        stmt.bindLong(7, entity.getPageCode());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }

    @Override
    public TaskInfo readEntity(Cursor cursor, int offset) {
        TaskInfo entity = new TaskInfo( //
                cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // objectId
                cursor.getLong(offset + 2), // executeTime
                cursor.getString(offset + 3), // codeName
                cursor.getInt(offset + 4), // excutionStatus
                cursor.getInt(offset + 5), // companyId
                cursor.getInt(offset + 6) // pageCode
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, TaskInfo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setObjectId(cursor.getLong(offset + 1));
        entity.setExecuteTime(cursor.getLong(offset + 2));
        entity.setCodeName(cursor.getString(offset + 3));
        entity.setExcutionStatus(cursor.getInt(offset + 4));
        entity.setCompanyId(cursor.getInt(offset + 5));
        entity.setPageCode(cursor.getInt(offset + 6));
     }
     
    @Override
    public Long getKey(TaskInfo entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final Long updateKeyAfterInsert(TaskInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /**
     * Properties of entity TaskInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, long.class, "objectId", false, "OBJECT_ID");
        public final static Property ExecuteTime = new Property(2, long.class, "executeTime", false, "EXECUTE_TIME");
        public final static Property CodeName = new Property(3, String.class, "codeName", false, "CODE_NAME");
        public final static Property ExcutionStatus = new Property(4, int.class, "excutionStatus", false, "EXCUTION_STATUS");
        public final static Property CompanyId = new Property(5, int.class, "companyId", false, "COMPANY_ID");
        public final static Property PageCode = new Property(6, int.class, "pageCode", false, "PAGE_CODE");
    }

    @Override
    public boolean hasKey(TaskInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
